### ISSUE TITLE
 Update is no longer compatible with your system: v0.3.0 to v0.4.0

### ISSUE THREAD

**Issue by emouawad** [hassio-addons/addon-glances#12]
I am running Glances on Ubuntu 18.04.2 LTS within Oracle VM VirtualBox - on Win10-64bit
Had 0.3.0 running now 0.4.0 refuses to update - with "This update is no longer compatible with your system." What do i need to do get this update or is it true it can't be run on my installation?

![image](https://user-images.githubusercontent.com/6771272/56600970-9ce91700-6602-11e9-99b2-147ca5bd8534.png)

**Comment by emouawad** [comment]
`ERROR (MainThread) [hassio.addons.addon] Add-on a0d7b954_glances not supported on qemux86-64 with ['amd64', 'i386'] architecture`

**Comment by tjorim** [comment]
Make sure your Home Assistant installation is running the latest version (0.91.4).

**Comment by frenck** [comment]
Yep the add-on needs HA 0.91.4+
