### ISSUE TITLE
Enable SMART monitor sensors?

### ISSUE THREAD

**Issue by jds11111** [hassio-addons/addon-glances#162]
#Add SMART monitoring to Glances integration

> Glances provides a tremendous amount of data from a server, including recently roosting on the status of hard drives from SMART monitoring. This monitoring is crucial for getting signs that a drive is about to fail, and can be used to avoid catastrophic data losses at the worst, or signicant downtime at the least.

However, the HA integration does not provide this sensor as an entity, at least according to the docs or the list of available entities in my integration. Adding the sensor would be natural for home automation, especially if you have a data or media server.

## Expected behavior

> SMART sensors in Glances integration

## Actual behavior

> not implemented

## Steps to reproduce

> Enable SMART monitoring on your instance of glances using the '--enable-plugin smart' when running. Check the entities available in the glances integration of home assistant.

## Proposed changes

> Add the sensor

**Comment by sinclairpaul** [comment]
This is the Glances addon not the integration, you would need to raise a feature request on the Home Assistant Forums.
