### ISSUE TITLE
Glances fails to start due to `bad light userdata pointer`

### ISSUE THREAD

**Issue by charlietomo** [hassio-addons/addon-glances#18]
# Problem/Motivation

> Trying to install and run glances and it fails.

## Expected behavior

> Glances runs and I get to see stats of my system.

## Actual behavior

> Add on fails to start
`PANIC: unprotected error in call to Lua API (bad light userdata pointer)`

## Steps to reproduce

> Clean install of Hassio on Odroid C1, download Glances Add-on, try and start it.

## Proposed changes

> I suspect my issue is the same issue impacting a number of add-ons, related to using the `aarch64` architecture (the only option I'm aware of on an Odroid C1). I hope the same fix that has been done for other add-ons (e.g. Node Red) can be applied to this, time permitting, so it can work. I see the readme says Supports aarch64 Architecture, so I hope it is a temporary glitch.

**Comment by charlietomo** [comment]
> Potential duplicates:
> 
> * [#15] Glances Addon fails to start (78%)

Confirming this is NOT a duplicate.

**Comment by frenck** [comment]
This issue has been resolved in the latest release.
