### ISSUE TITLE
Support InfluxDB v2 Configuration for Glances

### ISSUE THREAD

**Issue by potomacenigma** [hassio-addons/addon-glances#205]
# Problem/Motivation

Addon doesn't currently support InfluxDB v2  configuration parameters for Glances per:
https://glances.readthedocs.io/en/latest/gw/influxdb.html?highlight=influxdb

## Expected behavior

Addon will support InfluxDB v2 configuration parameters.

## Actual behavior

Addon doesn't currently support InfluxDB v2  configuration parameters.

## Steps to reproduce

Try to connect to InfluxDB v2 instance.

## Proposed changes

Possible solution below:
![image](https://user-images.githubusercontent.com/35106401/134824262-41d94c2d-d03c-41f6-907a-95d658b1136d.png)
![image](https://user-images.githubusercontent.com/35106401/134824271-15410ac1-d37c-440c-9999-e0d669dc6717.png)

**Comment by frenck** [comment]
This is a feature request, not an issue.
