### ISSUE TITLE
loop keyword deprecated and will fail in Home Assistant after 2022.2

### ISSUE THREAD

**Issue by AF360** [hassio-addons/addon-glances#237]
# Problem/Motivation

> According to the log file the used loop-keyword is deprecated and will fail in HA after version 2022.2

## Expected behavior

No Warning-message in the logfile

## Actual behavior

Warning message in the Home Assistant (2021.12) log:

`Detected integration that called async_timeout.timeout with loop keyword argument. The loop keyword argument is deprecated and calls will fail after Home Assistant 2022.2. **Please report issue for glances using this method at homeassistant/components/glances/__init__.py, line 125: await self.api.get_data()**
`
(Source: helpers/frame.py:103

## Steps to reproduce

Fresh install Glances

**Comment by frenck** [comment]
You are mixing up add-ons and integrations.

This is the add-on repository and issue tracker, your report is about an integration.

**Comment by AF360** [comment]
Thanks, Frenck. 
I’m new to HA so please bear with me. 
I’ve now opened the issue with HA-Integrations here: https://github.com/home-assistant/core/issues/61910 <https://github.com/home-assistant/core/issues/61910>

Best,
Andreas
