### ISSUE TITLE
CPU Temp

### ISSUE THREAD

**Issue by jeremyoha450** [hassio-addons/addon-glances#246]
# Problem/Motivation

i dont see CPU temp at all.

## Expected behavior

i Would like to see CPU Temp

## Actual behavior

No CPU Temp

## Steps to reproduce

Dont know

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Right.. So, do you have any information for me?  For example, CPU specs? Installation type you  are running? Maybe the output of `ha info` from the command line?

As in, there is not much info  in this issue report for me to work with 🤷
