### ISSUE TITLE
Built-In Disk Sensors

### ISSUE THREAD

**Issue by lullerboi** [hassio-addons/addon-glances#248]
Hello,

I'm trying to find a way to represent these values (most importantly "/backup") as a sensor in the UI:

![grafik](https://user-images.githubusercontent.com/71088451/152070226-a2ee3f7d-dd5a-449c-983c-e6bb54f4a1d7.png)

Sadly, the built-in sensors will always show the same values for "used" and "used %":

![grafik](https://user-images.githubusercontent.com/71088451/152070353-d776e628-f843-4859-8e16-a30d5595fa22.png)

Do you see any way to access the "real" values?

Thank you in advance.

**Comment by frenck** [comment]
I'm not sure what you are reporting here? An issue with the Home Assistant integration?

**Comment by lullerboi** [comment]
Hello and thanks for your fast reply. I'm sorry for the confusion, I'll try to clarify.

I'm using your community add-on and the Glances integration on my HA Blue (all latest versions).
The integration will give you access to the sensors in question. However, these sensors will always report the same values for all sub-folders. That makes them pretty useless, you can easily get the same result if only using a "systemmonitor" sensor for "/".

Or is there another way to access the "/backup" size in HA? It is nicely visible inside Glances already! :(

I think you're right and this report should be moved to the integration issues, I'm terribly sorry. Are you able to move it or do I have to create a new issue?

**Comment by frenck** [comment]
Yeah, this is an integration issue. I cannot help with that from an add-on side of things.

I cannot move the issue. Home Assistant is a different project.

Issues with Home Assistant Core can be reported here: <https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
