### ISSUE TITLE
Glances no longer writes to influxDB

### ISSUE THREAD

**Issue by stealthmidget** [hassio-addons/addon-glances#25]
# Problem/Motivation

> I noticed after updating hassio and all add-ons that glances is no longer writing to InfluxDB.

## Expected behavior

> Data continuing to be written to the database

## Actual behavior

> On startup of the Glances add-on in hassio, I get the following alert:
INFO: Starting Glances...
INFO: Starting NGinx...
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
Traceback (most recent call last):
  File "/usr/bin/glances", line 11, in <module>
    load_entry_point('Glances==3.1.1', 'console_scripts', 'glances')()
  File "/usr/lib/python3.7/site-packages/glances/__init__.py", line 140, in main
    start(config=config, args=args)
  File "/usr/lib/python3.7/site-packages/glances/__init__.py", line 106, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/lib/python3.7/site-packages/glances/standalone.py", line 49, in __init__
    self.stats = GlancesStats(config=config, args=args)
  File "/usr/lib/python3.7/site-packages/glances/stats.py", line 47, in __init__
    self.load_modules(self.args)
  File "/usr/lib/python3.7/site-packages/glances/stats.py", line 101, in load_modules
    self.load_exports(args=args)
  File "/usr/lib/python3.7/site-packages/glances/stats.py", line 179, in load_exports
    config=self.config)
  File "/usr/lib/python3.7/site-packages/glances/exports/glances_influxdb.py", line 60, in __init__
    self.client = self.init()
  File "/usr/lib/python3.7/site-packages/glances/exports/glances_influxdb.py", line 70, in init
    ssl=(self.protocol.lower() == 'https'),
AttributeError: 'NoneType' object has no attribute 'lower'

This is Glances version 0.5.1 on Hassio version 0.96.4. I am writing to databases via other add-ons as well, those are not broken.

## Steps to reproduce

> Start Hassio, start Glances

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

<blockquote><img src="https://avatars0.githubusercontent.com/u/7390180?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/openresty/luajit2">openresty/luajit2</a></strong></div><div>OpenResty's Branch of LuaJIT 2. Contribute to openresty/luajit2 development by creating an account on GitHub.</div></blockquote>
<blockquote><div><strong><a href="https://openresty.org/en/download.html">OpenResty - Download</a></strong></div></blockquote>

**Comment by neophitus** [comment]
Im having the same issue here :( 
Any tips to solve?

**Comment by FreddyLauwers** [comment]
Can confirm same issue and errors in log.
Using:
- Add-on version: 0.5.1
-  System: Ubuntu 18.04.2 LTS  (amd64 / qemux86-64)
-  Home Assistant version: 0.96.5
-  Supervisor version: 170

**Comment by unw1red** [comment]
I can confirm same issue with Hassio on Raspberry Pi 4.

Add-on version: 0.5.1
System: hass.io (64-bit/Raspberry Pi 4)
Home Assistant version: 0.96.5
Supervisor version: 170

**Comment by madmic1314** [comment]
Am having the same issue - same error at line 70 as reported above.

**Comment by sinclairpaul** [comment]
The Openresty log is not relevant to the issue, actual problem seems to be caused by https://github.com/nicolargo/glances/blob/3286e83ee07fdbfb27fc80e754deccacb7bf6882/glances/exports/glances_influxdb.py#L44

Above PR should resolve by adding config to specify the protocol used.
