### ISSUE TITLE
Unable to download Glances from Add On

### ISSUE THREAD

**Issue by Rudysmama** [hassio-addons/addon-glances#267]
# Problem/Motivation

> I receive an error when I try to download Glances through the Add On store.  

## Expected behavior

> Previous experience just installed glances.  

## Actual behavior

> Received the following error: 

Failed to install add-on
Can't install ghcr.io/hassio-addons/glances/aarch64:0.16.0: 404 Client Error for http+docker://localhost/v1.41/images/ghcr.io/hassio-addons/glances/aarch64:0.16.0/json: Not Found ("no such image: ghcr.io/hassio-addons/glances/aarch64:0.16.0: No such image: ghcr.io/hassio-addons/glances/aarch64:0.16.0")

## Steps to reproduce

> Try to download directly from Add On store.  

## Proposed changes

> No proposed fix.

**Comment by hertzg** [comment]
This is weird :thinking: , the image seems to be there and tagged correctly. The image arch and manifest also seems correct.

https://github.com/hassio-addons/addon-glances/pkgs/container/glances%2Faarch64/25003428?tag=0.16.0

```
hertz@potato:~$ docker inspect ghcr.io/hassio-addons/glances/aarch64:0.16.0
[
    {
        "Id": "sha256:784b065a0fc6340a881ce64c2c0b96141e6fdb3257c2dabae390272b6302241f",
        "RepoTags": [
            "ghcr.io/hassio-addons/glances/aarch64:0.16.0"
        ],
        "RepoDigests": [
            "ghcr.io/hassio-addons/glances/aarch64@sha256:7a1d08902984ead65dbd3eadc6d9e7442a4ce3c6719aea73eedd74f2d965a43e"
        ],
        ...
        "Config": {
            ...
            "Labels": {
                "io.hass.arch": "aarch64",
                ...
                "org.opencontainers.image.version": "0.16.0"
            },
			...
        },
        "Architecture": "arm64",
        "Os": "linux",
        "Size": 109791427,
        "VirtualSize": 109791427,
        ...
    }
]

```

**Comment by frenck** [comment]
![CleanShot 2022-06-22 at 15 21 13](https://user-images.githubusercontent.com/195327/175039345-2a30717b-dc1a-41d2-9276-5c19466de6ff.png)

Seems like it cannot be found in your local registry (thus failed downloading).

You could try running `ha supervisor repair` to fix it.

**Comment by hertzg** [comment]
> `ha supervisor repair`
It timed out eventually but fixed the issue for me. Thanks

**Comment by Rudysmama** [comment]
Thank you!  I was able to download it!  Thanks for a quick response!

**Comment by frenck** [comment]
Alright! good to hear it was resolved, will close the issue on this end in that case 👍
