### ISSUE TITLE
Credentials for sensor?

### ISSUE THREAD

**Issue by fredrikbaberg** [hassio-addons/addon-glances#27]
# Problem/Motivation

When adding the sensor in Home Assistant, it is not clear what "YOUR_GLANCES_USERNAME" and "YOUR_GLANCES_PASSWORD" are supposed to be.

## Expected behavior

Description that Home Assistant credentials are to be used, or where to set other credentials if needed.

## Actual behavior

Not stated.

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

Add a line to the description how to add a sensor which mentions that Home Assistant credentials are used would be useful.
I created a new user for this, not sure if that is needed/useful - but it keeps me from entering my main user password in the secrets.yaml file.

**Comment by rgabrielson11** [comment]
In the documentation for the sensor for HA, there is the following config example:

sensor:
  - platform: glances
    host: 127.0.0.1
    username: YOUR_GLANCES_USERNAME
    password: YOUR_GLANCES_PASSWORD
    version: 3
    resources:
      - 'processor_load'
      - 'memory_use_percent'
      - 'disk_use_percent'

However, the    " username: YOUR_GLANCES_USERNAME" and "
    password: YOUR_GLANCES_PASSWORD" config or defaults are not configured anywhere.  I have also tried the default 'glances','' to no avail.

**Comment by sinclairpaul** [comment]
Documentation for the sensor is at https://www.home-assistant.io/components/glances/ 

It is linked in the readme and both Username and Password are listed as optional. This doesn't appear to be an issue with the addon itself so closing out.

**Comment by sinclairpaul** [comment]
I'm going to reopen this as we need to update the docs:

1. Under Ingress only I'm thinking this would not work

2. With the addon exposed its lua auth so needs to be HA authentication.

**Comment by rgabrielson11** [comment]
Correct.

**Comment by sinclairpaul** [comment]
PR is done, the following should work:
`sensor:
  - platform: glances
    host: localhost
    port: 61209
    version: 3
    resources:
      - 'processor_load'
      - 'memory_use_percent'
      - 'disk_use_percent'`

**Comment by sinclairpaul** [comment]
Will close out for now.
