### ISSUE TITLE
cannot read api/3/cpu load since yesterday 7pm gmt

### ISSUE THREAD

**Issue by alsacian** [hassio-addons/addon-glances#29]
I use this in configuration.yaml and without any change it stopped working yesterday at about 7pm GMT
- platform: rest
  resource: http://192.168.1.20:8082/api/3/cpu
  username: ****
  password: ********
  name: CPU usage
  value_template: '{{ value_json.total}}'
  unit_of_measurement: "%"

if I enter manualy:
http://192.168.1.20:8082/api/3/cpu
I get asked for username and password wich never work (hassio username and password)
and get error message : 401 Access Denied

**Comment by bratanon** [comment]
Same issue here. Cant access the API anymore.

**Comment by BlueBlueBlob** [comment]
Same here with glances component : 401

**Comment by sinclairpaul** [comment]
Please update to the Hass.io supervisor v181 and retest.  The issue should be resolved.

**Comment by alsacian** [comment]
It is working, thanks
