### ISSUE TITLE
Glances Web User Interface started on http://127.0.0.1:61209/

### ISSUE THREAD

**Issue by nutsofamily** [hassio-addons/addon-glances#317]
installed glances in hassio on pi4. Can access from web interface from dashboard but cannot add any sensors to lovelace.
Glances Web User Interface started on http://127.0.0.1:61209/ is not accessible nor is substituting 127.0... with ip of local hassio install.

**Comment by frenck** [comment]
See: https://github.com/hassio-addons/addon-glances/blob/main/glances/DOCS.md#adding-glances-as-a-sensor-into-home-assistant
