### ISSUE TITLE
Improvement : Ability to change the path to the configuration file glances.conf

### ISSUE THREAD

**Issue by chrsc59** [hassio-addons/addon-glances#318]
# Problem/Motivation

> (Why the issue was filed)
We need a way to change the location of the configuration file
```/config/glances/glances.conf``` seems to be hard-coded

## Expected behavior

> (What you expected to happen)
An input field in the configuration UI (as with most of addons)

## Actual behavior

> (What actually happened)
No way to change the path

## Steps to reproduce

> (How can someone else make/see it happen)
N/A or go to the configuration UI
file goes to ```/config/glances/glances.conf```

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

Many HA addons have this field available in the addon configuration UI, that seems a quite "standard" feature for addons configuration.

**Comment by frenck** [comment]
Sorry I have no interest in adding such options. Above all, the configuration path suggested is officially dedicated to Home Assistant configuration (and not glances).

There is an RFC open @ the Home Assistant Supervisor project that would implement public/user-facing folders for each individual add-on. If that would be implement I would be happy to just put everything there.

Until that time, I'm going to friendly decline this suggestion.

../Frenck
