### ISSUE TITLE
glances now fails to start after working well for some time

### ISSUE THREAD

**Issue by iannecj** [hassio-addons/addon-glances#32]
# Problem/Motivation

glances fails to start

## Expected behavior

glances starts

## Actual behavior

glances attempts to start but fails ....this is the relevant entries in log:

`19-09-11 01:21:01 WARNING (SyncWorker_9) [hassio.docker.addon] Glances run with disabled protected mode!
19-09-11 01:21:01 INFO (SyncWorker_9) [hassio.docker.interface] Clean addon_a0d7b954_glances application
19-09-11 01:21:38 INFO (SyncWorker_17) [hassio.docker.addon] Start Docker add-on homeassistant/armv7-addon-samba with version 8.1
19-09-11 01:21:38 ERROR (SyncWorker_9) [hassio.docker] Can't start addon_a0d7b954_glances: 500 Server Error: Internal Server Error ("OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"/var/run/docker.sock\\\" to rootfs \\\"/mnt/data/docker/overlay2/688809efc974efb562c49b857c3d887b20348c3447184cb2d80f0ec62784bf23/merged\\\" at \\\"/var/run/docker.sock\\\" caused \\\"lstat /mnt/data/docker/overlay2/688809efc974efb562c49b857c3d887b20348c3447184cb2d80f0ec62784bf23/merged/var: bad message\\\"\"": unknown")
19-09-11 01:21:40 INFO (SyncWorker_18) [hassio.docker.addon] Start Docker add-on hassioaddons/influxdb-armv7 with version 3.2.1
19-09-11 01:21:40 INFO (SyncWorker_4) [hassio.docker.addon] Start Docker add-on hassioaddons/grafana-armv7 with version 2.2.5
19-09-11 01:21:40 INFO (SyncWorker_15) [hassio.docker.addon] Start Docker add-on homeassistant/armv7-addon-ssh with version 6.3
19-09-11 01:21:41 INFO (SyncWorker_11) [hassio.docker.addon] Start Docker add-on hassioaddons/unifi-armv7 with version 0.12.0
19-09-11 01:21:41 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished coro=<Addon.start() done, defined at /usr/src/hassio/hassio/addons/addon.py:457> exception=AddonsError()>
Traceback (most recent call last):
  File "/usr/src/hassio/hassio/addons/addon.py", line 478, in start
    raise AddonsError() from None
hassio.exceptions.AddonsError`

## Steps to reproduce

I setup glances with influx.  glance in sidebar worked fine.  data in influx and plotted in grafana fine.  Just noticed (2 or three updates have occured since I checked glances) glances not running and cannot be started from hassio add on page.

## Proposed changes

get glances to start

**Comment by sinclairpaul** [comment]
Is there an addon startup log?  Is this on HassOS?

**Comment by iannecj** [comment]
There is no text in addon startup log even after a refresh.  This is on
hass.io

**Comment by iannecj** [comment]
Also here is the balance of the system log in hassio gui on HA:

System log

19-09-11 01:21:40 INFO (SyncWorker_18) [hassio.docker.addon] Start
Docker add-on hassioaddons/influxdb-armv7 with version 3.2.119-09-11
01:21:40 INFO (SyncWorker_4) [hassio.docker.addon] Start Docker add-on
hassioaddons/grafana-armv7 with version 2.2.519-09-11 01:21:40 INFO
(SyncWorker_15) [hassio.docker.addon] Start Docker add-on
homeassistant/armv7-addon-ssh with version 6.319-09-11 01:21:41 INFO
(SyncWorker_11) [hassio.docker.addon] Start Docker add-on
hassioaddons/unifi-armv7 with version 0.12.019-09-11 01:21:41 ERROR
(MainThread) [asyncio] Task exception was never retrieved
future: <Task finished coro=<Addon.start() done, defined at
/usr/src/hassio/hassio/addons/addon.py:457> exception=AddonsError()>
Traceback (most recent call last):
  File "/usr/src/hassio/hassio/addons/addon.py", line 478, in start
    raise AddonsError() from None
hassio.exceptions.AddonsError19-09-11 01:21:48 INFO (MainThread)
[hassio.api.security] /host/info access from a0d7b954_unifi19-09-11
01:21:48 INFO (MainThread) [hassio.api.security] /host/info access
from a0d7b954_grafana19-09-11 01:21:48 INFO (MainThread)
[hassio.api.security] /host/info access from a0d7b954_influxdb19-09-11
01:21:50 INFO (MainThread) [hassio.api.security] /dns/info access from
a0d7b954_influxdb19-09-11 01:21:50 INFO (SyncWorker_19)
[hassio.docker.interface] Clean homeassistant application19-09-11
01:22:13 INFO (SyncWorker_19) [hassio.docker.homeassistant] Start
homeassistant homeassistant/raspberrypi4-homeassistant with version
0.98.519-09-11 01:22:28 INFO (MainThread) [hassio.homeassistant] Home
Assistant pip installation in progress19-09-11 01:23:54 INFO
(MainThread) [hassio.homeassistant] Home Assistant pip installation
done19-09-11 01:24:04 INFO (MainThread) [hassio.homeassistant] Detect
a running Home Assistant instance19-09-11 01:24:04 INFO (MainThread)
[hassio.addons] Phase 'application' start 1 add-ons19-09-11 01:24:36
INFO (SyncWorker_12) [hassio.docker.addon] Start Docker add-on
homeassistant/armv7-addon-configurator with version 3.419-09-11
01:24:41 INFO (MainThread) [hassio.tasks] All core tasks are
scheduled19-09-11 01:24:41 INFO (MainThread) [hassio.core] Hass.io is
up and running19-09-11 01:35:47 ERROR (MainThread)
[hassio.api.ingress] Ingress error: Cannot connect to host
172.30.32.1:63691 ssl:None [Connection refused]19-09-11 01:36:47
WARNING (SyncWorker_14) [hassio.docker.addon] Glances run with
disabled protected mode!19-09-11 01:36:47 INFO (SyncWorker_14)
[hassio.docker.interface] Clean addon_a0d7b954_glances
application19-09-11 01:36:50 ERROR (SyncWorker_14) [hassio.docker]
Can't start addon_a0d7b954_glances: 500 Server Error: Internal Server
Error ("OCI runtime create failed: container_linux.go:345: starting
container process caused "process_linux.go:430: container init caused
\"rootfs_linux.go:58: mounting \\\"/var/run/docker.sock\\\" to rootfs
\\\"/mnt/data/docker/overlay2/0af2aaf7a08076f04b8a35ac4e2083031a2915aaab67ae8c327b0c26f4839531/merged\\\"
at \\\"/var/run/docker.sock\\\" caused \\\"lstat
/mnt/data/docker/overlay2/0af2aaf7a08076f04b8a35ac4e2083031a2915aaab67ae8c327b0c26f4839531/merged/var:
bad message\\\"\"": unknown")19-09-11 01:38:17 ERROR (MainThread)
[hassio.api.ingress] Ingress error: Cannot connect to host
172.30.32.1:63691 ssl:None [Connection refused]19-09-11 01:42:08 ERROR
(MainThread) [hassio.api.ingress] Ingress error: Cannot connect to
host 172.30.32.1:63691 ssl:None [Connection refused]19-09-11 03:24:41
INFO (MainThread) [hassio.updater] Fetch update data from
https://version.home-assistant.io/stable.json19-09-11 04:24:41 INFO
(MainThread) [hassio.store.git] Update add-on
https://github.com/home-assistant/hassio-addons repository19-09-11
04:24:41 INFO (MainThread) [hassio.store.git] Update add-on
https://github.com/hassio-addons/repository repository19-09-11
04:24:42 ERROR (MainThread) [hassio.store.git] Can't update
https://github.com/home-assistant/hassio-addons repo: Cmd('git')
failed due to: exit code(128)
  cmdline: git fetch --depth=1 --update-shallow -v origin
  stderr: 'error: inflate: data stream error (incorrect header check)
error: unable to unpack e86cbd891ec70fac6926f45c999ca7be482ed1e3 header
fatal: loose object e86cbd891ec70fac6926f45c999ca7be482ed1e3 (stored
in .git/objects/e8/6cbd891ec70fac6926f45c999ca7be482ed1e3) is corrupt
error: remote did not send all necessary objects'.19-09-11 04:24:43
INFO (MainThread) [hassio.store] Load add-ons from store: 60 all - 0
new - 0 remove19-09-11 05:24:42 INFO (MainThread) [hassio.updater]
Fetch update data from
https://version.home-assistant.io/stable.json19-09-11 07:24:41 INFO
(MainThread) [hassio.store.git] Update add-on
https://github.com/hassio-addons/repository repository19-09-11
07:24:41 INFO (MainThread) [hassio.store.git] Update add-on
https://github.com/home-assistant/hassio-addons repository19-09-11
07:24:42 INFO (MainThread) [hassio.updater] Fetch update data from
https://version.home-assistant.io/stable.json19-09-11 07:24:42 ERROR
(MainThread) [hassio.store.git] Can't update
https://github.com/home-assistant/hassio-addons repo: Cmd('git')
failed due to: exit code(128)
  cmdline: git fetch --depth=1 --update-shallow -v origin
  stderr: 'error: inflate: data stream error (incorrect header check)
error: unable to unpack e86cbd891ec70fac6926f45c999ca7be482ed1e3 header
fatal: loose object e86cbd891ec70fac6926f45c999ca7be482ed1e3 (stored
in .git/objects/e8/6cbd891ec70fac6926f45c999ca7be482ed1e3) is corrupt
error: remote did not send all necessary objects'.19-09-11 07:24:42
INFO (MainThread) [hassio.store] Load add-ons from store: 60 all - 0
new - 0 remove19-09-11 09:24:42 INFO (MainThread) [hassio.updater]
Fetch update data from
https://version.home-assistant.io/stable.json19-09-11 10:14:33 ERROR
(MainThread) [aiohttp.server] Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py",
line 448, in start
    await resp.write_eof()
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_response.py",
line 444, in write_eof
    await self._payload_writer.write_eof(data)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/http_writer.py",
line 138, in write_eof
    self._write(chunk)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/http_writer.py",
line 67, in _write
    raise ConnectionResetError('Cannot write to closing transport')
ConnectionResetError: Cannot write to closing transport19-09-11
10:15:13 ERROR (MainThread) [hassio.api.ingress] Ingress error: Cannot
connect to host 172.30.32.1:63691 ssl:None [Connection
refused]19-09-11 10:15:26 INFO (MainThread) [hassio.homeassistant]
Updated Home Assistant API token19-09-11 10:24:41 INFO (MainThread)
[hassio.store.git] Update add-on
https://github.com/home-assistant/hassio-addons repository19-09-11
10:24:41 INFO (MainThread) [hassio.store.git] Update add-on
https://github.com/hassio-addons/repository repository19-09-11
10:24:42 ERROR (MainThread) [hassio.store.git] Can't update
https://github.com/home-assistant/hassio-addons repo: Cmd('git')
failed due to: exit code(128)
  cmdline: git fetch --depth=1 --update-shallow -v origin
  stderr: 'error: inflate: data stream error (incorrect header check)
error: unable to unpack e86cbd891ec70fac6926f45c999ca7be482ed1e3 header
fatal: loose object e86cbd891ec70fac6926f45c999ca7be482ed1e3 (stored
in .git/objects/e8/6cbd891ec70fac6926f45c999ca7be482ed1e3) is corrupt
error: remote did not send all necessary objects'.19-09-11 10:24:42
INFO (MainThread) [hassio.store] Load add-ons from store: 60 all - 0
new - 0 remove19-09-11 10:48:57 INFO (MainThread)
[hassio.homeassistant] Updated Home Assistant API token19-09-11
11:24:42 INFO (MainThread) [hassio.updater] Fetch update data from
https://version.home-assistant.io/stable.json19-09-11 13:24:41 INFO
(MainThread) [hassio.store.git] Update add-on
https://github.com/home-assistant/hassio-addons repository19-09-11
13:24:42 INFO (MainThread) [hassio.store.git] Update add-on
https://github.com/hassio-addons/repository repository19-09-11
13:24:42 INFO (MainThread) [hassio.updater] Fetch update data from
https://version.home-assistant.io/stable.json19-09-11 13:24:42 ERROR
(MainThread) [hassio.store.git] Can't update
https://github.com/home-assistant/hassio-addons repo: Cmd('git')
failed due to: exit code(128)
  cmdline: git fetch --depth=1 --update-shallow -v origin
  stderr: 'error: inflate: data stream error (incorrect header check)
error: unable to unpack e86cbd891ec70fac6926f45c999ca7be482ed1e3 header
fatal: loose object e86cbd891ec70fac6926f45c999ca7be482ed1e3 (stored
in .git/objects/e8/6cbd891ec70fac6926f45c999ca7be482ed1e3) is corrupt
error: remote did not send all necessary objects'.19-09-11 13:24:42
INFO (MainThread) [hassio.store] Load add-ons from store: 60 all - 0
new - 0 remove

**Comment by sinclairpaul** [comment]
It's not an issue with the addon, as it isn't launching, its an issue primarily with Docker.  It could possibly the signs of file system issues (SD Card?), you could attempt to remove and re-install the addon to see if it helps.
