### ISSUE TITLE
Issue with influxdb2 after update to 0.18.0

### ISSUE THREAD

**Issue by askpet** [hassio-addons/addon-glances#325]
# Problem/Motivation

> Running HAOS on an Odroid N2+. Just updated to Glances 0.18 with support for for influxdb2.

I have filled in information for influxdb2 (has waited for this :-D )

I am getting this error in the log:

-----------------------------------------------------------
 Add-on: Glances
 A cross-platform system monitoring tool
-----------------------------------------------------------
 Add-on version: 0.18.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.5  (aarch64 / odroid-n2)
 Home Assistant Core: 2023.3.4
 Home Assistant Supervisor: 2023.03.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
INFO: Starting Glances...
Glances Web User Interface started on http://127.0.0.1:61209/
INFO: Starting NGinx...
Traceback (most recent call last):
  File "/usr/bin/glances", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/glances/__init__.py", line 179, in main
    start(config=core.get_config(), args=core.get_args())
  File "/usr/lib/python3.10/site-packages/glances/__init__.py", line 108, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/lib/python3.10/site-packages/glances/standalone.py", line 45, in __init__
    self.stats = GlancesStats(config=config, args=args)
  File "/usr/lib/python3.10/site-packages/glances/stats.py", line 39, in __init__
    self.load_modules(self.args)
  File "/usr/lib/python3.10/site-packages/glances/stats.py", line 90, in load_modules
    self.load_exports(args=args)
  File "/usr/lib/python3.10/site-packages/glances/stats.py", line 167, in load_exports
    self._exports[export_name] = export_module.Export(args=args, config=self.config)
  File "/usr/lib/python3.10/site-packages/glances/exports/glances_influxdb.py", line 51, in __init__
    self.client = self.init()
  File "/usr/lib/python3.10/site-packages/glances/exports/glances_influxdb.py", line 65, in init
    db = InfluxDBClient(
  File "/usr/lib/python3.10/site-packages/influxdb/client.py", line 115, in __init__
    self.__port = int(port)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**My yaml conf**:
log_level: info
process_info: false
refresh_time: 10
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
influxdb:
  enabled: true
  host: 192.168.50.182
  port: 8086
  interval: 30
  ssl: false
  version: 2
  username: user
  password: pass
  database: data
  prefix: Odroid
  token: "!secret myinfluxdb2token"
  bucket: Glances
  org: Home

## Expected behavior

> I expected that it would send data to influxdb2

## Actual behavior

> Glances gui is running - but no data to influxdb2

## Steps to reproduce

> install 0.18.0 and fill out information for version: 2

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by mplogas** [comment]
Same here, 

integration version: 1.18.0
influxdb version: 2.6.1
config:
```yaml
enabled: true
host: 192.168.<redacted>
port: 8086
interval: 60
ssl: false
version: 2
username: glances
password: ""
database: glances
prefix: <redacted>
token: >-
  <redacted>
bucket: <redacted>
org: <redacted>
```

**Comment by fr1cklr** [comment]
Same here :(

**Comment by G4KCM** [comment]
Same problem ☹️

**Comment by timpendlebury** [comment]
Same problem

**Comment by mariuszxeno** [comment]
Same problem

**Comment by gatonero** [comment]
I guess the connection shoul be now **[influxdb 2]**. But this you can't change by yourself even not in Yaml editor. It throws an error.
https://glances.readthedocs.io/en/latest/gw/influxdb.html?highlight=influxdb

**Comment by sanghviharshit** [comment]
Weirdly, It stopped working for me for influxdb v1 after this update! I can't get it to work with either v1 or v2. Same error.

**Comment by frenck** [comment]
0.18.1 should be better...let us know :)

**Comment by G4KCM** [comment]
> 

👍 It works for me.  Thank you!

**Comment by mariuszxeno** [comment]
> 0.18.1 should be better...let us know :)

it's ok, it came back after update
