### ISSUE TITLE
Unknown options warnings in supervisor

### ISSUE THREAD

**Issue by willem-ebbers** [hassio-addons/addon-glances#328]
# Problem/Motivation

> when I start  docker logs --follow hassio_supervisor I notice some WARNING logs coming from glances.

```
23-03-23 15:27:27 WARNING (MainThread) [supervisor.addons.options] Unknown option 'version' for Glances (a0d7b954_glances)
23-03-23 15:27:27 WARNING (MainThread) [supervisor.addons.options] Unknown option 'token' for Glances (a0d7b954_glances)
23-03-23 15:27:27 WARNING (MainThread) [supervisor.addons.options] Unknown option 'bucket' for Glances (a0d7b954_glances)
23-03-23 15:27:27 WARNING (MainThread) [supervisor.addons.options] Unknown option 'org' for Glances (a0d7b954_glances)

```

![image](https://user-images.githubusercontent.com/60136106/227235149-17d0aa98-a235-41c7-92a0-936071723f0f.png)

the latest glances is installed on my system (0.18.0) and it is working as normal

## Expected behavior

> no effect in homeassistant noticable, expect not to see any warning logs in supervisor

## Actual behavior

> no effect in homeassistant noticable

## Steps to reproduce

> see screenshot above.

## Proposed changes

> is there something I need to do on my installation or should this be fixed with an update of the addon?
> I tried to remove the specific option lines in the configuration "edit in yaml" option, but when I click save these options re-appear.

**Comment by frenck** [comment]
fixed in #329
