### ISSUE TITLE
Endpoint with name already exists in network host

### ISSUE THREAD

**Issue by lukasleitsch** [hassio-addons/addon-glances#33]
# Problem/Motivation

The addon don't start in my setup. Raspberry Pi 3B+ with the current version of Hass.io. After loading the addon the following error appears in the system log of Hass.io

```
19-09-25 19:04:40 ERROR (SyncWorker_13) [hassio.docker] Can't start addon_a0d7b954_glances: 403 Client Error: Forbidden ("endpoint with name addon_a0d7b954_glances already exists in network host")
```

## Expected behavior

The addon should start without this error. Uninstall and reload of the addon don't resolve this issue.

## Actual behavior

The addon don't show logs. The only error is shown in the system log.

## Steps to reproduce

I have no idea how this behavior came up. I hope you'll have a idea to debug this error.

**Comment by sinclairpaul** [comment]
Can you run the following `hassio supervisor repair`

You can use the SSH addon to do so.

**Comment by lukasleitsch** [comment]
Thanks for your help. I did the following steps:

1. Uninstall the addon
2. Run the command `hassio supervisor repair`
3. Load the addon
4. Try to start the addon

Unfortunately, it still doesn't start. Same error.

**Comment by frenck** [comment]
This is unfortunately out of control for the add-on. Please raise an issue with Hassio or join the Home Assistant community forums/chat for support.
