### ISSUE TITLE
Containers Active/CPU usage/RAM Usage HA Sensors are unavailable after 19.x update.

### ISSUE THREAD

**Issue by ClaymoreTech4** [hassio-addons/addon-glances#370]
# Problem/Motivation

The containers active, containers CPU usage and RAM Usage HA sensor  is unavailable after update to 19.x.  Currently running 19.2.

## Expected behavior

Looking at the release notes, I don't see a breaking change for these sensors.

## Actual behavior

![image](https://github.com/hassio-addons/addon-glances/assets/67112140/cf0ead47-a73a-49c5-9cd2-9b8ccb76185c)

## Steps to reproduce

Upgrade to 19.x

**Comment by sinclairpaul** [comment]
What does the actual addon show when you open it? if it shows the container details then it would suggest that the issue may lie with the integration.

If it doesn't show the container information, please post the logs.

**Comment by ClaymoreTech4** [comment]
![image](https://github.com/hassio-addons/addon-glances/assets/67112140/58a3ca59-dfbe-4eae-976b-be25c086d858)

-----------------------------------------------------------
 Add-on: Glances
 A cross-platform system monitoring tool
-----------------------------------------------------------
 Add-on version: 0.19.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.1  (amd64 / qemux86-64)
 Home Assistant Core: 2023.5.4
 Home Assistant Supervisor: 2023.04.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
INFO: Starting Glances...
Glances Web User Interface started on http://127.0.0.1:61209/
INFO: Starting NGinx...

**Comment by sinclairpaul** [comment]
Your screenshot show's the container information (the section named Containers).  Therefore I would suggest that this is an issue with the HA integration in some way, and not related to the addon.
