### ISSUE TITLE
integration is not stating

### ISSUE THREAD

**Issue by lecasana** [hassio-addons/addon-glances#385]
# Problem/Motivation
Not starting...

## Expected behavior
to start

## Actual behavior
click start get a long time a back to intial (the button to strat)

## Steps to reproduce
click start after integration

## Proposed changes
??

**Comment by lecasana** [comment]
OS Version:               Home Assistant OS 10.3
  Home Assistant Core:      2023.7.1
on turenas scale VM (debian/docker)

No way to basically start it,
no log in basic page
log in system mentions no connection to sensors
google mentions: pip3 install python-dateutil
I am newbie  & dont find a way to acces pip on the VM

**Comment by sinclairpaul** [comment]
Post the log:
![image](https://github.com/hassio-addons/addon-glances/assets/24625998/c3315705-fcf9-487c-a888-0f09245a6c3b)

**Comment by lecasana** [comment]
-----------------------------------------------------------
 Add-on: Glances
 A cross-platform system monitoring tool
-----------------------------------------------------------
 Add-on version: 0.19.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.3  (amd64 / qemux86-64)
 Home Assistant Core: 2023.7.1
 Home Assistant Supervisor: 2023.07.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
FATAL: PROTECTION MODE IS ENABLED!
FATAL: 
FATAL: To be able to use this add-on, you'll need to disable
FATAL: protection mode on this add-on. Without it, the add-on
FATAL: is unable to access Docker.
FATAL: 
FATAL: Steps:
FATAL:  - Go to the Supervisor Panel.
FATAL:  - Click on this add-on.
FATAL:  - Set the 'Protection mode' switch to off.
FATAL:  - Restart the add-on.
FATAL: 
FATAL: Access to Docker allows you to do really powerful things
FATAL: including complete destruction of your system.
FATAL: Please, be sure you know what you are doing before
FATAL: enabling this feature (and this add-on)!
FATAL:

**Comment by sinclairpaul** [comment]
So did you follow the instructions that are in the log?

**Comment by lecasana** [comment]
no,
I just discover it by copy/paste,

just try it that works...
very sorry,
I was thinking that 1st pages option are add-on default set, not OS imposed ones ...
sorry ;)
