### ISSUE TITLE
username / password for external web interface

### ISSUE THREAD

**Issue by Ollie2304** [hassio-addons/addon-glances#407]
I'm trying to open the web interface using my browser.
I've defined under the network setting of the addon configuartion port: `61210`
When I go into my browser and type `192.168.0.54:61210` I get the username and password prompt.
However i'm not sure what these are or how to define them, i've tried to edit the glances.conf but it still doesn't let me login.
![Screenshot 2023-08-29 014346](https://github.com/hassio-addons/addon-glances/assets/70420879/808845e3-4ff2-4385-b754-901482582864)
Not sure if i'm doing it right...

**Comment by sinclairpaul** [comment]
Use your HA credentials
