### ISSUE TITLE
Glances appears to be adding localhost_vethXXXXX interfaces to my HA

### ISSUE THREAD

**Issue by jlongman** [hassio-addons/addon-glances#484]
# Problem/Motivation

Seeing constant addition of localhost_veth sensors added with different suffix hashes.  Currently showing 62, 44 are in status `Not Provided`.

On a PI4 running as below, Glances Add-On is 0.21.1
```
Core 2024.5.5
Supervisor 2024.05.1
Operating System 12.3
Frontend 20240501.1
```

<img width="781" alt="image" src="https://github.com/hassio-addons/addon-glances/assets/1051995/d6cffb11-0284-4d6e-81ba-e7c1c2319639">

## Expected behavior

either sensors should be stable or removed?

## Actual behavior

continually polluting entity space

## Steps to reproduce

unclear

## Proposed changes

?

---

Happy to help diagnose.

Current Addons installed: (is there a text way to get this?)
<img width="1017" alt="image" src="https://github.com/hassio-addons/addon-glances/assets/1051995/b2e3a1a8-aa64-4a85-a900-469ed882a7cf">

**Comment by steve-prentice** [comment]
Same issue here on my HA, 80+ entries at the moment, all marked unavailable.

**Comment by mkarnebeek** [comment]
Since a certain version, I think either glances, or the integration started supporting network interfaces. These network interfaces are created by docker and create new ones every time a container/addon updates.

This is solvable by setting the following in `glances.conf`
```
[network]
hide=veth*
```

But since we cannot influence `glances.conf` or the network section from the addon configuration, that's unsettable for me at the moment.

**Comment by sinclairpaul** [comment]
It was added to the integration <https://github.com/home-assistant/core/pull/114546>

> But since we cannot influence glances.conf or the network section from the addon configuration, that's unsettable for me at the moment.

The glances.conf file is currently at `/config/glances/glances.conf`, you should be able to edit it there.

**Comment by mkarnebeek** [comment]
Awesome! Tnx for that info. I'll try this tomorrow evening. Maybe an idea to add this to the documentation, or by default hide veth interfaces?

**Comment by sinclairpaul** [comment]
The logic today won't overwrite existing installs.  Considering that this isn't just related to the addon itself, I would suggest that the integration may need to deal with ignoring certain entities.
