### ISSUE TITLE
Temp Sensor data is not coming through to Home Assistant Glances addon

### ISSUE THREAD

**Issue by tehfonz** [hassio-addons/addon-glances#488]
# Problem/Motivation

If I visit the Glances webui I see temp sensors for CPU and HDDs, however the glances addon in Home Assistant is not bringing that data in as entities.

I am running:
Home Assistant:
```
Core               2024.6.2
Supervisor         2024.06.0
Operating System   12.3
Frontend           20240605.0
```
Glances:
```
Glances version:        4.0.5
Glances API version:    4
PsUtil version:         5.9.8
```
ProxMox
```
Proxmox: 8.2.2
```
## Expected behavior

On a previous installation of Proxmox and Glances I had the temperature sensor data in Home Assistant, this time around I can't see anything.

## Actual behavior

No temp sensors are coming through, however all other sensors are coming through and are accurate.

## Steps to reproduce

Not really sure how to reproduce this issue for other installs.

## Troubleshooting Steps

I have restarted the node & Home Assistant. I have reinstalled Glances, restarted glances and am still unable to get the data. I have uninstalled the Glances addon from Home Assistant and still no temp sensors. I initially followed this guide: https://www.derekseaman.com/2023/04/home-assistant-monitor-proxmox-with-glances.html
I have also followed a few other guides to no avail.

**Comment by sinclairpaul** [comment]
If the issue is with the Integration it would need to be logged with the Home Assistant repo.

As it is shown in the addon, there isn't much that can be done here.

**Comment by tehfonz** [comment]
My Bad! Thanks for the prompt reply :)
