### ISSUE TITLE
No cpu temp on Intel NUC

### ISSUE THREAD

**Issue by jchasey** [hassio-addons/addon-glances#50]
# Problem/Motivation

Missing sensor

## Expected behavior

Sensor to be present

## Actual behavior

No sensors for temperature appear

## Steps to reproduce

Install on Intel NUC, start add-on

## Proposed changes

From the glances docs, it appears that lmsensors should be installed on OS and then the sensors would be available

**Comment by sinclairpaul** [comment]
What Operating system are you running?

**Comment by jchasey** [comment]
Hostname | hassio
-- | --
System | HassOS 3.9
Deployment | production

**Comment by jchasey** [comment]
arch | x86_64
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.6
timezone | UTC
version | 0.105.1
virtualenv | false

**Comment by sinclairpaul** [comment]
Will let @frenck confirm here, but I believe the underlying issue is the module in the OS itself, for which the addon cannot influence.

**Comment by frenck** [comment]
Correct, the add-on will catch the values available but has no influence on the system itself.

This cannot be fixed by the add-on.
