### ISSUE TITLE
Removed bridge network entities are not removed

### ISSUE THREAD

**Issue by janusn** [hassio-addons/addon-glances#500]
# Problem/Motivation

> (Why the issue was filed)
A bridge network comes and goes when a docker container is downed/pulled on the target machine. As images are updated frequently, there are tons of left over network entities for the devices under glances integration.
![Screenshot 2024-08-25 at 01 03 38](https://github.com/user-attachments/assets/080a583a-6ade-4b6d-847c-e36ddd419b1b)

## Expected behavior

> (What you expected to happen)

The network entities should be removed when the corresponding network is removed from the target machine running glances.

## Actual behavior

> (What actually happened)
The network entity of the removed network remains and becomes unavailable.

## Steps to reproduce

> (How can someone else make/see it happen)

1. add a devices for the glances on home assistant integration.
2. remove a bridge network on the target machine.
3. check the entities under the device.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

When a bridge network of the target system removed, the entity of the corresponding device is not removed from the integration.

**Comment by sinclairpaul** [comment]
This would be an issue for the integration not the addon, would suggest you log it there.
