### ISSUE TITLE
Glances ports option?

### ISSUE THREAD

**Issue by mattlward** [hassio-addons/addon-glances#52]
# Problem/Motivation

Want to monitor a couple of sites and systems

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

Is is possible to add support for ports in the Glances addon?
https://glances.readthedocs.io/en/stable/aoa/ports.html

Thanks Matt

<blockquote><div><strong><a href="https://glances.readthedocs.io/en/stable/aoa/ports.html">Ports — Glances 3.1.3 documentation</a></strong></div></blockquote>

**Comment by frenck** [comment]
You can customize your configuration, it is located in `/config/glances/`

👍
