### ISSUE TITLE
Trouble with long link info in GUI

### ISSUE THREAD

**Issue by ahadata** [hassio-addons/addon-glances#58]
![long-link](https://user-images.githubusercontent.com/60839982/77410193-ce420800-6dba-11ea-8c73-b5360b627599.png)
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
This is not a bug with the add-on, but with Glances itself.
Add-ons wrap existing software, in this case, Glances.

Please report the issue with the Glances project. Thanks! 👍
