### ISSUE TITLE
Which hostname/IP address to use when setting up Glances

### ISSUE THREAD

**Issue by lsilva171** [hassio-addons/addon-glances#67]
# Problem/Motivation

Using latest Hass.io and add-glances versions.
Set up the integration through Configuration -> Integrations -> Glances
I used localhost, 127.0.0.1, the name of the container and all failed to connect

## Expected behavior

Set up the integration through Configuration -> Integrations -> Glances using localhost as hostname should successfully connect

## Actual behavior

Integration setup fails with error "Unable to connect to host"

Set up the integration through Configuration -> Integrations -> Glances
Accept the default values and click on submit

## Proposed changes

Using Portainer there's no ports being exposed for addon-glances container so not not sure if port 61208 externally is accessible. This may be the root of the problem

**Comment by frenck** [comment]
https://github.com/hassio-addons/addon-glances#adding-glances-as-a-sensor-into-home-assistant

**Comment by lsilva171** [comment]
> https://github.com/hassio-addons/addon-glances#adding-glances-as-a-sensor-into-home-assistant
> 
> > <img alt="" width="48" src="https://avatars1.githubusercontent.com/u/30772201?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/040b5519c6d1891329f5f6d3e511003657131cf2/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[hassio-addons/addon-glances](https://github.com/hassio-addons/addon-glances)**Glances - Home Assistant Community Add-ons. Contribute to hassio-addons/addon-glances development by creating an account on GitHub.

It doesn't seem to work since after following the instructions above the following error shows in the logs

Log Details (ERROR)
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:112
Integration: Sensor (documentation, issues)
First occurred: 1:11:33 PM (1 occurrences)
Last logged: 1:11:33 PM

The glances platform for the sensor integration does not support platform setup. Please remove it from your config.

**Comment by sinclairpaul** [comment]
Please note the port to use:

![image](https://user-images.githubusercontent.com/24625998/81506233-e61a1080-92c2-11ea-98c4-49d5aad83bae.png)

**Comment by lsilva171** [comment]
> Please note the port to use:
> 
> ![image](https://user-images.githubusercontent.com/24625998/81506233-e61a1080-92c2-11ea-98c4-49d5aad83bae.png)

Using 61209 as port number worked.

Thx for the tip.
