### ISSUE TITLE
Glances Entities Not updating

### ISSUE THREAD

**Issue by lordmach** [hassio-addons/addon-glances#74]
My Glances Entities are not updating and and show as unavailable. It has been working and started to do it intermittently but now its this way 100%. Any ideas of what could cause this?

Thank you!

**Comment by frenck** [comment]
Hi there @lordmach,

Thanks for opening up an issue. The add-on does not provide entities, that is what a integration does.

Please check <https://www.home-assistant.io/help> for information on getting support with Home Assistant Core integration.

Thanks 👍
