### ISSUE TITLE
history_size remains to 28800

### ISSUE THREAD

**Issue by Adorem** [hassio-addons/addon-glances#77]
# Problem/Motivation

Hi,

Like describe here: #61 I also see memory leaks.

Then I update the addon from v0.7.1 to v0.8.0 to take advantage of this correction:
https://github.com/hassio-addons/addon-glances/commit/302a49afd1fb7d60fc55f80e104439462a0e04b0

## Expected behavior

In /etc/glances.conf I expect the value for history_size to be 0

## Actual behavior

but it remains to 28800

## Steps to reproduce

Update from from v0.7.1 to v0.8.0

## Proposed changes

For the moment as a workaround I manually update /config/glances/glances.conf to include this change and keep it through the addon restart.

**Comment by sinclairpaul** [comment]
The change updates the defaults from when first installing, it doesn't change any existing config, as you can set it yourself.

**Comment by Adorem** [comment]
Thanks for your answer. I remembered that vscode addon was able to update the config if it was unchanged by the user as explained here:
https://github.com/hassio-addons/addon-vscode/blob/master/vscode/DOCS.md#resetting-your-vscode-settings-to-the-add-on-defaults

And it seems to be thanks to this code:
https://github.com/hassio-addons/addon-vscode/blob/master/vscode/rootfs/etc/cont-init.d/code-server.sh

Maybe something that can be used here too?
