### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by cconde** [hassio-addons/addon-glances#88]
# Problem/Motivation

Despite the addon starts, page doesn't show

## Expected behavior

Show something after clicking the Glances button of the sidebar

## Actual behavior

There's a single line saying 502 Bad Gateway

## Steps to reproduce

I just installed the addon, started and tried to access
There's no error under the "Log" page of HomeAssistant (don't know if it's supposed to appear here)

## Proposed changes

Help?

**Comment by cconde** [comment]
Additional info: it seems the addon stops after a while.

Restarting doesn't help

**Comment by sinclairpaul** [comment]
For anyone to help you would need to post the addon log:

![image](https://user-images.githubusercontent.com/24625998/93005816-d20d4680-f522-11ea-800c-fcc1c27351a1.png)

And also the supervisor log, Supervisor, System, System Log.

**Comment by cconde** [comment]
Thank you,

I've just managed to solve it right now but I take note for future requests

**Comment by bertman42** [comment]
For anyone looking for a potential workaround.  I fixed this by toggling the Protection mode to off.

![image](https://user-images.githubusercontent.com/7479927/99115531-904f5980-25c0-11eb-947d-421934525dba.png)
